spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jackson:
    default-property-inclusion: non_null
    serialization:
      fail-on-empty-beans: false

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  h2:
    console:
      enabled: true
kafka:
  bootstrap-servers: localhost:9092


