spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/dev
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    logging:
      level:
        org.hibernate.type.descriptor.sql: trace


springdoc:
  swagger-ui:
    path: /api-test
    groups-order: DESC
    tags-sorter: alpha
